// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3XJhUPwtsXooswHpwiI_uT_4y7yxRHJA',
    appId: '1:745729891371:web:5e9bd0d6f5677d12075e6e',
    messagingSenderId: '745729891371',
    projectId: 'tareamovil-3614b',
    authDomain: 'tareamovil-3614b.firebaseapp.com',
    storageBucket: 'tareamovil-3614b.firebasestorage.app',
    measurementId: 'G-2TH0VLV60V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPURKcdD3R31XhFeTjPz2jPnZc4_LkW10',
    appId: '1:745729891371:android:f12be444bd230bcc075e6e',
    messagingSenderId: '745729891371',
    projectId: 'tareamovil-3614b',
    storageBucket: 'tareamovil-3614b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWwCiIoRhhGwZnkJVxKxJh38UMU5E4Ck0',
    appId: '1:745729891371:ios:78299a6865a73b6e075e6e',
    messagingSenderId: '745729891371',
    projectId: 'tareamovil-3614b',
    storageBucket: 'tareamovil-3614b.firebasestorage.app',
    iosBundleId: 'com.example.examen2doparcial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWwCiIoRhhGwZnkJVxKxJh38UMU5E4Ck0',
    appId: '1:745729891371:ios:78299a6865a73b6e075e6e',
    messagingSenderId: '745729891371',
    projectId: 'tareamovil-3614b',
    storageBucket: 'tareamovil-3614b.firebasestorage.app',
    iosBundleId: 'com.example.examen2doparcial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3XJhUPwtsXooswHpwiI_uT_4y7yxRHJA',
    appId: '1:745729891371:web:4cce1aed808a219c075e6e',
    messagingSenderId: '745729891371',
    projectId: 'tareamovil-3614b',
    authDomain: 'tareamovil-3614b.firebaseapp.com',
    storageBucket: 'tareamovil-3614b.firebasestorage.app',
    measurementId: 'G-FF12MVT5L1',
  );
}
